# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c31b0a45c06938f2587f351b41809e4987551ea3006e7dcbf952f3f98b8860713a62bfdeeeb75eb4b06ae3facbf34bab0b7f74077b47ada358165819a76286

test:
  secret_key_base: bfba8ca60db21b168638022ab30436bea11cf52e2131a2d0a3a7f0819a52f8d89aa034db4feeaa3af462187126d7ea7fd71fb6a8f70e06f50fc5aa9eca392053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
